### ISSUE TITLE
Error in `$<-.data.frame`(`*tmp*`, "EM", value = c(NA_character_, NA_character_ :  replacement has 2 rows, data has 1

### ISSUE THREAD

**Issue by oguzozbay** [ropensci/refsplitr#77]
I installed refsplitr package as follows:
install.packages("remotes")
remotes::install_github("embruna/refnet2")
---
For the sake of simplicity, I've given my data the same name as in your example.
I runed the example code and because of errors I cleanend NA's as follows.

dat1 <- dat1 %>% filter(!is.na(AU)) 
dat1 <- dat1 %>% filter(!is.na(AF)) 
dat1 <- dat1 %>% filter(!is.na(EM))

However, when I run the code below:
dat2 <- authors_clean(references = dat1)
I got the following error.

Error in `$<-.data.frame`(`*tmp*`, "EM", value = c(NA_character_, NA_character_ :  replacement has 2 rows, data has 1

Do you have an idea for the solution.
Best regards.

**Comment by oguzozbay** [comment]
Possibly I found the problem.
I am trying it know.
I changed all ; to , in EM collumn.
The code is still runnig and did not give an error.
Because my data is bir, it will possibly take an hour.
I will write the result.

**Comment by embruna** [comment]
From an author email to EMB: " I changed all semicolons (;) to comma (,) in EM collumn, error is disappeared"
