### ISSUE TITLE
Docs building failure

### ISSUE THREAD

**Issue by maelle** [ropensci/refsplitr#83]
:wave: @embruna!

We're seeing some failures in https://github.com/r-universe/ropensci/actions/runs/1574868026 in particular when trying to build the pkgdown website https://github.com/r-universe/ropensci/runs/4511976198?check_suite_focus=true (maybe the vignette should be pre-built? Cf https://ropensci.org/blog/2019/12/08/precompute-vignettes/)

I also see you're using Travis, which we no longer recommend https://ropensci.org/blog/2020/11/19/moving-away-travis/ so for future checks you might want to explore e.g. GitHub Actions see https://usethis.r-lib.org/reference/github_actions.html and https://github.com/r-lib/actions/tree/v2-branch/examples

Happy to provide guidance if needed.

**Comment by embruna** [comment]
Hi @maelle, I'll deal with this as soon as I return from vacation on January 2. If it needs to be done sooner, just let me know.

**Comment by maelle** [comment]
:wave: @embruna! A friendly reminder in case this slipped through the cracks, and a Happy New Year in any case!

**Comment by embruna** [comment]
Happy New Year, @maelle! I've switched over from Travis to Github Actions. I think I scribbed Travis completely, the one doubt I had was what to do with the appveyor.yaml but I will look into that in a bit.

**Comment by embruna** [comment]
As for the failures, i think they are definitely the vignette and will try the pre-built option ASAP.

**Comment by maelle** [comment]
:wave: @embruna!

> the one doubt I had was what to do with the appveyor.yaml but I will look into that in a bit.

I think you can remove this too as GitHub Actions also supports CI on Windows.

**Comment by maelle** [comment]
The docs website is up, thank you!

**Comment by embruna** [comment]
> 

Removed appveyor.yaml . Still trying to figure out why failing but getting closer

**Comment by maelle** [comment]
Maybe you need to deactivate the repo in Appveyor interface? It's under your Appveyor account right? (If I remember correctly we no longer transferred them to ropensci account even when we still used Appveyor)
