### ISSUE TITLE
README.md doesn't match README.Rmd

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [ropensci/refsplitr#89]
https://github.com/ropensci/refsplitr/blob/38c01e609cbdf1ad28bc7c6a89de1e433892eb10/README.md?plain=1#L37-L38
is duplicated on lines
https://github.com/ropensci/refsplitr/blob/38c01e609cbdf1ad28bc7c6a89de1e433892eb10/README.md?plain=1#L40-L41
in the README.md file but not in the README.Rmd file. I am guessing the former was edited manually rather than being
dynamically created from the latter?

**Comment by embruna** [comment]
yup...thanks!
