### ISSUE TITLE
Action needed before 2023-01-25: update refsplitr's dependencies as it cannot be built

### ISSUE THREAD

**Issue by maelle** [ropensci/refsplitr#90]
:wave: @embruna!

Your refsplitr package cannot be built on R-universe as it depends on the deprecated spatial package maptools. See for instance this [write up by Jakub Nowosad to understand the changes in the R spatial ecosystem](https://geocompx.org/post/2023/rgdal-retirement/index.html). :world_map: 

**Please indicate us before January, the 25th whether you intend to update your package.** If not, we will archive refsplitr* and remove it from rOpenSci registry. You do not need to make changes before January, the 25th; but you do need to drop us a line before then.

You can find [help](https://devdevguide.netlify.app/maintenance_cheatsheet), among other places, in our Slack's workspace "spatial" and "package-maintenance" channels.

Thank you! :pray:

*: We can unarchive the repository and transfer it to your own account, at your request. We won't shred it. :smile_cat: 

@ropensci/admin

**Comment by maelle** [comment]
I was made aware of planned updates in a separate conversation :smile_cat:

**Comment by maelle** [comment]
@embruna I see all builds are failing on https://ropensci.r-universe.dev/builds, any update, any help needed?

cc @ropensci/admin

**Comment by embruna** [comment]
Hi, I have just started my sabbatical, and Item #2 on the list is to deal with the issues with dependencies etc for refsplitr -  with some luck I will start on this coming Monday.  I'll be sure to ask for help if - errr, when - I need it!

**Comment by maelle** [comment]
Awesome! I'll be off for the next three weeks. https://devguide.ropensci.org/maintenance_cheatsheet.html

**Comment by embruna** [comment]
I removed the line of code related to maptools, the builds are [no long failing](https://ropensci.r-universe.dev/builds). The R-CMD-check is still failing, but this appears to be [due to a few warnings](https://github.com/ropensci/refsplitr) (1 deprecated command, one non-ASCII character).

**Comment by embruna** [comment]
UPDATE: all cmd-checks are now passing and addressed issue of non-ascii character.

**Comment by maelle** [comment]
:tada: :rocket:
